### ISSUE TITLE
Proposals

### ISSUE THREAD

**Issue by ghost** [OpenAssets/open-assets-protocol#6]
I'm new to github and for the life of me can't figure out how to make a pull request or proposal, but I created three proposals to update OA with that I was hoping you might be interested in.

They are:

- Expanding the specification to allow the use of P2SH addresses to issue assets.  This is useful for say a corporation issuing assets and shareholders know that multiple members of the board must cooperate in order to issue more.

- Adding "nmc=oa/NAME" to the optional OP_RETURN metadata so that Namecoin names can be used for asset definitions.

- Standardizing the use of compressed keys, since it appears in the specification and in most asset issaunces that I saw on the blockchain that most keys being use are uncompressed.

The proposal mediawikis are at:

https://github.com/7trXMk6Z/openassets_expansion_proposals

Thanks for your time, and excellent work on this fantastic colored coin implementation!

**Comment by asifshiraz** [comment]
I recently subscribed to this project as its seems very interesting. What I
did was to fork from the original repo, which then lets you create pull
requests back. Your repo appears to be a stand alone one, and not forked
from the main one. Could be that? Not sure.

**Comment by Flavien** [comment]
Thanks for your comments @7trXMk6Z.

* Regarding P2SH, the current OA specification makes no assumption on the type of script used for issuance. It can be P2PKH as well as P2SH, as well as any other type of script. The process for computing the asset ID is the same in all the cases (a hash of the script), and no special case is needed. 
* Regarding compressed vs. uncompressed keys, again, OA makes no assumption on the type of key being used. You can already use both. The reason why you mostly see compressed keys on the blockchain is because Coinprism is the main client for OA and currently supports only compressed keys. But again, the protocol doesn't need to make any assumption on the type of key.
* I will get back to you on the Namecoin proposal, as this is something that can be interesting to have.
